name: Run APIs Daily

on:
  schedule:
    # Run daily at 18:15 UTC (11:45 PM IST)
    - cron: "15 18 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  run-apis:
    runs-on: ubuntu-latest
    steps:
      - name: Call CoinDCX API
        run: curl -X GET https://volume-scapper.onrender.com/coin-dcx-past-24h-volume?market=INR
      - name: Call CoinSwitch API
        run: curl -X GET https://volume-scapper.onrender.com/coin-switch-past-24h-volume?market=INR
